name: PR — Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nextjsLibreria

    services:
      mongodb:
        image: mongo:7.0
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: test
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    env:
      MONGODB_URL: "mongodb://root:password@localhost:27017/test?authSource=admin&retryWrites=true&w=majority"
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./nextjsLibreria/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Wait for MongoDB
        run: |
          timeout 60 bash -c 'until mongosh --host localhost:27017 --eval "db.runCommand({ ping: 1 })" --quiet; do sleep 2; done'
        shell: bash

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Push database schema
        run: npx prisma db push

      - name: Build Next.js
        run: npm run build
